# Generated by Django 4.2.1 on 2023-06-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_alter_watchlist_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
