# Generated by Django 4.2.1 on 2023-06-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_mal_id'),
        ('watchlist', '0005_rename_isactive_watchlist_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='anime_list',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='anime_list',
            field=models.ManyToManyField(blank=True, null=True, to='anime.anime'),
        ),
    ]
