# Generated by Django 4.2.1 on 2023-06-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_mal_id'),
        ('watchlist', '0006_remove_watchlist_anime_list_watchlist_anime_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='anime_list',
            field=models.ManyToManyField(blank=True, to='anime.anime'),
        ),
    ]
