# Generated by Django 4.2.1 on 2023-06-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0007_alter_watchlist_anime_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='anime_list',
        ),
    ]
