# Generated by Django 4.2.1 on 2023-06-14 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_mal_id'),
        ('watchlist', '0008_remove_watchlist_anime_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0, max_length=10)),
                ('review', models.CharField(blank=True, max_length=1000, null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.anime')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.watchlist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
