# Generated by Django 4.2.1 on 2023-06-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_created_on_alter_post_modified_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
    ]
